package Visao;

import Controle.ControleLivro;
import Modelo.Livro;
import Modelo.persistencia.LivroDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Flávio
 */
public class CadastrarLivro extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarLivro
     */
    public CadastrarLivro() {
        initComponents();
        this.setLocation(300, 65);
        try {
            lerTabela();
        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void lerTabela() {

        List<Livro> listLivros = new ArrayList<>();
        listLivros.addAll(new LivroDao().listarTodos());

        DefaultTableModel modelo = (DefaultTableModel) this.tabelaLivros.getModel();
        this.tabelaLivros.setRowSorter(new TableRowSorter(modelo));
        modelo.setNumRows(0);

        for (Livro livro : listLivros) {
            modelo.addRow(new Object[]{livro.getId(), livro.getIsbn(), livro.getTitulo(), livro.getSubtitulo(),
                livro.getEdicao(), livro.getPaginas(), livro.getLocal(), livro.getEditora(), livro.getAno()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIsbnLivro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTituloLivro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSubTituloLivro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEdicaoLivro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPaginasLivro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLocalLivro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEditoraLivro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAnoLivro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtIdLivro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaLivros = new javax.swing.JTable();
        btnSalvarLivro = new javax.swing.JButton();
        btnEditarLivro = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setTitle("Cadastrar Livro");
        setPreferredSize(new java.awt.Dimension(760, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Novo livro"));

        jLabel2.setText("ISBN:");

        jLabel3.setText("Titulo:");

        jLabel4.setText("Subtítulo:");

        jLabel5.setText("Edição:");

        jLabel6.setText("Páginas:");

        txtPaginasLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaginasLivroActionPerformed(evt);
            }
        });

        jLabel7.setText("Local:");

        jLabel8.setText("Editora:");

        txtEditoraLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditoraLivroActionPerformed(evt);
            }
        });

        jLabel9.setText("Ano:");

        jLabel1.setText("Id:");

        txtIdLivro.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEditoraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEdicaoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPaginasLivro)
                            .addComponent(txtAnoLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLocalLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSubTituloLivro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIsbnLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIsbnLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSubTituloLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEdicaoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPaginasLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtLocalLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEditoraLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtAnoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Lista de livros")));
        jPanel2.setToolTipText("Lista de livros");

        tabelaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "ISBN", "Titulo", "Subtitulo", "Ediçao", "Pag.", "Local", "Editora", "Ano"
            }
        ));
        tabelaLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaLivrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaLivros);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSalvarLivro.setText("Salvar");
        btnSalvarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLivroActionPerformed(evt);
            }
        });

        btnEditarLivro.setText("Alterar");
        btnEditarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLivroActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnSalvarLivro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEditarLivro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimpar))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarLivro)
                    .addComponent(btnEditarLivro)
                    .addComponent(btnLimpar))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaginasLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaginasLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaginasLivroActionPerformed

    private void txtEditoraLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditoraLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditoraLivroActionPerformed

    private void btnSalvarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLivroActionPerformed
        try {
            long isbn = Long.parseLong(this.txtIsbnLivro.getText());
            String titulo = this.txtTituloLivro.getText();
            String subtitulo = this.txtSubTituloLivro.getText();
            String edicao = this.txtEdicaoLivro.getText();
            int paginas = Integer.parseInt(this.txtPaginasLivro.getText());
            String local = this.txtLocalLivro.getText();
            String editora = this.txtEditoraLivro.getText();
            int ano = Integer.parseInt(this.txtAnoLivro.getText());
            new ControleLivro().cadastrar(new Livro(isbn, titulo, subtitulo, edicao, paginas, local, editora, ano));
            this.tabelaLivros.setToolTipText("");
            this.txtAnoLivro.setText("");
            this.txtEdicaoLivro.setText("");
            this.txtEditoraLivro.setText("");
            this.txtIsbnLivro.setText("");
            this.txtLocalLivro.setText("");
            this.txtPaginasLivro.setText("");
            this.txtSubTituloLivro.setText("");
            this.txtTituloLivro.setText("");
            lerTabela();
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, new NumberFormatException("Dados inválidos para os campos").getMessage());
        }

    }//GEN-LAST:event_btnSalvarLivroActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.txtIdLivro.setText("");
        this.tabelaLivros.setToolTipText("");
        this.txtAnoLivro.setText("");
        this.txtEdicaoLivro.setText("");
        this.txtEditoraLivro.setText("");
        this.txtIsbnLivro.setText("");
        this.txtLocalLivro.setText("");
        this.txtPaginasLivro.setText("");
        this.txtSubTituloLivro.setText("");
        this.txtTituloLivro.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void tabelaLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaLivrosMouseClicked
        int indice = this.tabelaLivros.getSelectedRow();
        this.txtIdLivro.setText(this.tabelaLivros.getValueAt(indice, 0).toString());
        this.txtIsbnLivro.setText(this.tabelaLivros.getValueAt(indice, 1).toString());
        this.txtTituloLivro.setText(this.tabelaLivros.getValueAt(indice, 2).toString());
        this.txtSubTituloLivro.setText(this.tabelaLivros.getValueAt(indice, 3).toString());
        this.txtEdicaoLivro.setText(this.tabelaLivros.getValueAt(indice, 4).toString());
        this.txtPaginasLivro.setText(this.tabelaLivros.getValueAt(indice, 5).toString());
        this.txtLocalLivro.setText(this.tabelaLivros.getValueAt(indice, 6).toString());
        this.txtEditoraLivro.setText(this.tabelaLivros.getValueAt(indice, 7).toString());
        this.txtAnoLivro.setText(this.tabelaLivros.getValueAt(indice, 8).toString());
    }//GEN-LAST:event_tabelaLivrosMouseClicked

    private void btnEditarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLivroActionPerformed

        long id = Long.parseLong(this.txtIdLivro.getText());
        long isbn = Long.parseLong(this.txtIsbnLivro.getText());
        String titulo = this.txtTituloLivro.getText();
        String subtitulo = this.txtSubTituloLivro.getText();
        String edicao = this.txtEdicaoLivro.getText();
        int paginas = Integer.parseInt(this.txtPaginasLivro.getText());
        String local = this.txtLocalLivro.getText();
        String editora = this.txtEditoraLivro.getText();
        int ano = Integer.parseInt(this.txtAnoLivro.getText());
        new ControleLivro().alterar(new Livro(id, isbn, titulo, subtitulo, edicao, paginas, local, editora, ano));
        this.txtIdLivro.setText("");
        this.tabelaLivros.setToolTipText("");
        this.txtAnoLivro.setText("");
        this.txtEdicaoLivro.setText("");
        this.txtEditoraLivro.setText("");
        this.txtIsbnLivro.setText("");
        this.txtLocalLivro.setText("");
        this.txtPaginasLivro.setText("");
        this.txtSubTituloLivro.setText("");
        this.txtTituloLivro.setText("");
        lerTabela();

    }//GEN-LAST:event_btnEditarLivroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarLivro;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvarLivro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaLivros;
    private javax.swing.JTextField txtAnoLivro;
    private javax.swing.JTextField txtEdicaoLivro;
    private javax.swing.JTextField txtEditoraLivro;
    private javax.swing.JTextField txtIdLivro;
    private javax.swing.JTextField txtIsbnLivro;
    private javax.swing.JTextField txtLocalLivro;
    private javax.swing.JTextField txtPaginasLivro;
    private javax.swing.JTextField txtSubTituloLivro;
    private javax.swing.JTextField txtTituloLivro;
    // End of variables declaration//GEN-END:variables
}
