package Visao;

import Controle.ControleCitacao;
import Modelo.Autor;
import Modelo.Citacao;
import Modelo.Livro;
import Modelo.persistencia.AutorDao;
import Modelo.persistencia.CitacaoDao;
import Modelo.persistencia.LivroDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Flávio
 */
public class CadastrarCitacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarCitacao
     */
    public CadastrarCitacao() {
        initComponents();
        this.setLocation(300, 65);
        try {
            this.listaDeLivros.setModel(new DefaultComboBoxModel(new LivroDao().listarTodos().toArray()));
            this.listaDeAutores.setModel(new DefaultComboBoxModel(new AutorDao().listarTodos().toArray()));
            lerTabela();
            this.txtAreaCitacao.setLineWrap(true);

        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    public void lerTabela() {

        List<Citacao> listCitacoes = new ArrayList<>();
        listCitacoes.addAll(new CitacaoDao().listarTodos());

        DefaultTableModel modelo = (DefaultTableModel) this.tabelaCitacoes.getModel();
        this.tabelaCitacoes.setRowSorter(new TableRowSorter(modelo));
        modelo.setNumRows(0);

        for (Citacao citacao : listCitacoes) {
            modelo.addRow(new Object[]{citacao.getId(), citacao.getLivro(), citacao.getAutor(), citacao.getTexto()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        listaDeLivros = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        listaDeAutores = new javax.swing.JComboBox<>();
        txtLivroSelecionado = new javax.swing.JTextField();
        txtAutorSelecionado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtIdCitacao = new javax.swing.JTextField();
        btnSalvarLivro = new javax.swing.JButton();
        btnEditarLivro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCitacao = new javax.swing.JTextArea();
        btnLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCitacoes = new javax.swing.JTable();

        jCheckBox1.setText("jCheckBox1");

        setClosable(true);
        setTitle("Cadastrar Citação");
        setPreferredSize(new java.awt.Dimension(760, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nova citação"));

        jLabel6.setText("Livros:");

        listaDeLivros.setToolTipText("");
        listaDeLivros.setName("Selecione"); // NOI18N
        listaDeLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDeLivrosMouseClicked(evt);
            }
        });
        listaDeLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeLivrosActionPerformed(evt);
            }
        });

        jLabel7.setText("Autores:");

        listaDeAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDeAutoresMouseClicked(evt);
            }
        });
        listaDeAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDeAutoresActionPerformed(evt);
            }
        });

        txtLivroSelecionado.setEditable(false);

        txtAutorSelecionado.setEditable(false);

        jLabel1.setText("Id:");

        txtIdCitacao.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaDeAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtAutorSelecionado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdCitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listaDeLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLivroSelecionado)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdCitacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(listaDeLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLivroSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(listaDeAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutorSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listaDeLivros.getAccessibleContext().setAccessibleName("");

        btnSalvarLivro.setText("Salvar");
        btnSalvarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarLivroActionPerformed(evt);
            }
        });

        btnEditarLivro.setText("Editar");
        btnEditarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarLivroActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Texto (Citação)"));

        txtAreaCitacao.setColumns(20);
        txtAreaCitacao.setRows(5);
        txtAreaCitacao.setMaximumSize(new java.awt.Dimension(680, 2147483647));
        txtAreaCitacao.setMinimumSize(new java.awt.Dimension(1, 22));
        jScrollPane1.setViewportView(txtAreaCitacao);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastros"));

        tabelaCitacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Livro", "Autor", "Texto"
            }
        ));
        tabelaCitacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCitacoesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaCitacoes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvarLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarLivro)
                    .addComponent(btnEditarLivro)
                    .addComponent(btnLimpar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarLivroActionPerformed
        Livro livro = (Livro) this.listaDeLivros.getSelectedItem();
        Autor autor = (Autor) this.listaDeAutores.getSelectedItem();
        String citacao = this.txtAreaCitacao.getText();
        new ControleCitacao().cadastrar(new Citacao(livro, autor, citacao));
        lerTabela();
        this.txtIdCitacao.setText("");
        this.txtAreaCitacao.setText("");
        this.txtAutorSelecionado.setText("");
        this.txtLivroSelecionado.setText("");
    }//GEN-LAST:event_btnSalvarLivroActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.txtIdCitacao.setText("");
        this.txtAreaCitacao.setText("");
        this.txtAutorSelecionado.setText("");
        this.txtLivroSelecionado.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void listaDeLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDeLivrosActionPerformed

    }//GEN-LAST:event_listaDeLivrosActionPerformed

    private void listaDeAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDeAutoresActionPerformed

    }//GEN-LAST:event_listaDeAutoresActionPerformed

    private void tabelaCitacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCitacoesMouseClicked
        int indice = this.tabelaCitacoes.getSelectedRow();
        this.txtIdCitacao.setText(this.tabelaCitacoes.getValueAt(indice, 0).toString());
        this.txtLivroSelecionado.setText(this.tabelaCitacoes.getValueAt(indice, 1).toString());
        this.txtAutorSelecionado.setText(this.tabelaCitacoes.getValueAt(indice, 2).toString());
        this.txtAreaCitacao.setText(this.tabelaCitacoes.getValueAt(indice, 3).toString());
    }//GEN-LAST:event_tabelaCitacoesMouseClicked

    private void btnEditarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarLivroActionPerformed

        long id = Long.parseLong(this.txtIdCitacao.getText());
        Livro livro = (Livro) this.listaDeLivros.getSelectedItem();
        Autor autor = (Autor) this.listaDeAutores.getSelectedItem();
        String citacao = this.txtAreaCitacao.getText();
        new ControleCitacao().alterar(new Citacao(id, livro, autor, citacao));
        lerTabela();
        this.txtIdCitacao.setText("");
        this.txtAreaCitacao.setText("");
        this.txtAutorSelecionado.setText("");
        this.txtLivroSelecionado.setText("");

    }//GEN-LAST:event_btnEditarLivroActionPerformed

    private void listaDeLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeLivrosMouseClicked
        this.txtLivroSelecionado.setText(this.listaDeLivros.getSelectedItem().toString());
    }//GEN-LAST:event_listaDeLivrosMouseClicked

    private void listaDeAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeAutoresMouseClicked
        this.txtAutorSelecionado.setText(this.listaDeAutores.getSelectedItem().toString());
    }//GEN-LAST:event_listaDeAutoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarLivro;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvarLivro;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> listaDeAutores;
    private javax.swing.JComboBox<String> listaDeLivros;
    private javax.swing.JTable tabelaCitacoes;
    private javax.swing.JTextArea txtAreaCitacao;
    private javax.swing.JTextField txtAutorSelecionado;
    private javax.swing.JTextField txtIdCitacao;
    private javax.swing.JTextField txtLivroSelecionado;
    // End of variables declaration//GEN-END:variables
}
